.PHONY: build-ConnectionHandlerFunction build-GameActionHandlerFunction

build-ConnectionHandlerFunction:
	dotnet publish ChessOfCards.ConnectionHandler/ChessOfCards.ConnectionHandler.csproj -c Release -o $(ARTIFACTS_DIR)

build-GameActionHandlerFunction:
	dotnet publish ChessOfCards.GameActionHandler/ChessOfCards.GameActionHandler.csproj -c Release -o $(ARTIFACTS_DIR)
